#!/bin/sh
#wget http://buffalotech.com/support-and-downloads/download/nasnavi-278.zip
#wget http://buffalotech.com/support-and-downloads/download/nasnavi-279.dmg.zip
#wget http://www.buffalotech.com/support-and-downloads/download/nasnavi-282.zip
#wget http://www.buffalotech.com/support-and-downloads/download/nasnavi-282.dmg.zip
# Latest version for MS Windows is 3.0.4 - download requires cookie
wget https://dd00b71c8b1dfd11ad96-382cb7eb4238b9ee1c11c6780d1d2d1e.ssl.cf1.rackcdn.com/nasnavi-304.zip
