#!/bin/sh
#wget https://downloads.plex.tv/plex-media-server/0.9.11.7.803-87d0708/PlexMediaServer-0.9.11.7.803-87d0708-arm.spk
#wget https://downloads.plex.tv/plex-media-server/0.9.12.11.1406-8403350/PlexMediaServer-0.9.12.11.1406-8403350-arm.spk
wget https://downloads.plex.tv/plex-media-server/0.9.12.19.1537-f38ac80/PlexMediaServer-0.9.12.19.1537-f38ac80-arm.spk
# TODO: find latest armel / compatible Plex Media Server release, currently it's no longer available on the website (min ARMv7) - latest supported on ARMv5tel is 0.9.17.0
